pipeline: gracefully handle benign clap errors, i.e. printing the help message
This commit changes the way the pipeline emits errors when clap fails to parse
the command line arguments. Instead of treating all "abort"s as fatal errors, we
check that the errors from `clap` are not benign before terminating the pipeline
with the indication that the pipeline "failed".

For example, before hand we would print for `--version`:
```
error: hashc 0.1.0-3c6a02d0ca00b7c14e2e0622bfb724f4dbe68fc2
```

And after this, we print:
```
info: hashc 0.1.0-3c6a02d0ca00b7c14e2e0622bfb724f4dbe68fc2
```